-- ============================================
-- ETAPA 3 - DISEÑO FÍSICO
-- Data Warehouse Banco
-- Motor: PostgreSQL
-- ============================================
-- Opcional: crear esquema
CREATE SCHEMA IF NOT EXISTS DW_BANCO;

SET
	SEARCH_PATH TO DW_BANCO;

-- ============================================
-- DIMENSIONES
-- ============================================
CREATE TABLE DIM_TIEMPO (
	ID_TIEMPO INTEGER PRIMARY KEY,
	FECHA_COMPLETA DATE NOT NULL UNIQUE,
	DIA SMALLINT NOT NULL CHECK (DIA BETWEEN 1 AND 31),
	MES SMALLINT NOT NULL CHECK (MES BETWEEN 1 AND 12),
	NOMBRE_MES VARCHAR(20) NOT NULL,
	TRIMESTRE SMALLINT NOT NULL CHECK (TRIMESTRE BETWEEN 1 AND 4),
	SEMESTRE SMALLINT NOT NULL CHECK (SEMESTRE BETWEEN 1 AND 2),
	ANIO SMALLINT NOT NULL,
	DIA_SEMANA VARCHAR(20) NOT NULL
);

CREATE TABLE DIM_SUCURSAL (
	ID_SUCURSAL SERIAL PRIMARY KEY,
	CODIGO_SUCURSAL VARCHAR(20) NOT NULL UNIQUE,
	NOMBRE_SUCURSAL VARCHAR(100) NOT NULL,
	CIUDAD VARCHAR(100) NOT NULL,
	PROVINCIA VARCHAR(100),
	REGION VARCHAR(100),
	FECHA_INICIO_VIGENCIA DATE NOT NULL,
	FECHA_FIN_VIGENCIA DATE,
	REGISTRO_ACTUAL BOOLEAN NOT NULL DEFAULT TRUE,
	CHECK (
		FECHA_FIN_VIGENCIA IS NULL
		OR FECHA_FIN_VIGENCIA >= FECHA_INICIO_VIGENCIA
	)
);

CREATE TABLE DIM_TIPO_PRESTAMO (
	ID_TIPO_PRESTAMO SERIAL PRIMARY KEY,
	CODIGO_TIPO VARCHAR(20) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(100) NOT NULL
);

CREATE TABLE DIM_PROPOSITO (
	ID_PROPOSITO SERIAL PRIMARY KEY,
	CODIGO_PROPOSITO VARCHAR(20) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(100) NOT NULL
);

CREATE TABLE DIM_PRESTATARIO (
	ID_PRESTATARIO SERIAL PRIMARY KEY,
	CODIGO_PRESTATARIO VARCHAR(30) NOT NULL,
	FECHA_NACIMIENTO DATE,
  GENERO VARCHAR(1),
	ESTADO_CIVIL VARCHAR(30),
  PROPIEDAD VARCHAR(8),
	INGRESO_MENSUAL NUMERIC(18, 2) CHECK (INGRESO_MENSUAL >= 0),
	CANTIDAD_HIJOS INTEGER CHECK (CANTIDAD_HIJOS >= 0),
	DIRECCION VARCHAR(200),
	CIUDAD VARCHAR(100),
	PROVINCIA VARCHAR(100),
  CODIGO_PROVINCIA VARCHAR(2),
  CODIGO_POSTAL SMALLINT,
	FECHA_INICIO_VIGENCIA DATE NOT NULL,
	FECHA_FIN_VIGENCIA DATE,
	REGISTRO_ACTUAL BOOLEAN NOT NULL DEFAULT TRUE,
	CHECK (
		FECHA_FIN_VIGENCIA IS NULL
		OR FECHA_FIN_VIGENCIA >= FECHA_INICIO_VIGENCIA
	)
);

CREATE TABLE DIM_DESCUENTO (
	ID_DESCUENTO SERIAL PRIMARY KEY,
	CODIGO_DESCUENTO VARCHAR(20) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(100) NOT NULL,
	TIPO_DESCUENTO VARCHAR(50),
	PORCENTAJE_DESCUENTO NUMERIC(5, 2) CHECK (PORCENTAJE_DESCUENTO >= 0)
);

CREATE TABLE DIM_ESTADO_PRESTAMO (
	ID_ESTADO_PRESTAMO SERIAL PRIMARY KEY,
	CODIGO_ESTADO VARCHAR(20) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(50) NOT NULL
);

-- ============================================
-- TABLA DE HECHOS
-- ============================================
CREATE TABLE FACT_PRESTAMO (
	ID_FACT_PRESTAMO BIGSERIAL PRIMARY KEY,
	CODIGO_PRESTAMO_NEGOCIO VARCHAR(30) NOT NULL UNIQUE,
	ID_TIEMPO_INICIO INTEGER NOT NULL,
	ID_TIEMPO_FIN INTEGER,
	ID_SUCURSAL INTEGER NOT NULL,
	ID_TIPO_PRESTAMO INTEGER NOT NULL,
	ID_PROPOSITO INTEGER NOT NULL,
	ID_ESTADO_PRESTAMO INTEGER NOT NULL,
	MONTO_PRESTAMO NUMERIC(18, 2) NOT NULL CHECK (MONTO_PRESTAMO > 0),
	TASA_INTERES_INICIAL NUMERIC(5, 2) NOT NULL CHECK (TASA_INTERES_INICIAL >= 0),
	CANTIDAD_PRESTAMOS INTEGER NOT NULL DEFAULT 1 CHECK (CANTIDAD_PRESTAMOS = 1),
	CANTIDAD_DESCUENTOS_APLICADOS INTEGER NOT NULL DEFAULT 0 CHECK (CANTIDAD_DESCUENTOS_APLICADOS >= 0),
	INDICADOR_IMPAGO BOOLEAN NOT NULL DEFAULT FALSE,
	INDICADOR_PAGADO_COMPLETO BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT FK_FACT_TIEMPO_INICIO FOREIGN KEY (ID_TIEMPO_INICIO) REFERENCES DIM_TIEMPO (ID_TIEMPO),
	CONSTRAINT FK_FACT_TIEMPO_FIN FOREIGN KEY (ID_TIEMPO_FIN) REFERENCES DIM_TIEMPO (ID_TIEMPO),
	CONSTRAINT FK_FACT_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES DIM_SUCURSAL (ID_SUCURSAL),
	CONSTRAINT FK_FACT_TIPO_PRESTAMO FOREIGN KEY (ID_TIPO_PRESTAMO) REFERENCES DIM_TIPO_PRESTAMO (ID_TIPO_PRESTAMO),
	CONSTRAINT FK_FACT_PROPOSITO FOREIGN KEY (ID_PROPOSITO) REFERENCES DIM_PROPOSITO (ID_PROPOSITO),
	CONSTRAINT FK_FACT_ESTADO_PRESTAMO FOREIGN KEY (ID_ESTADO_PRESTAMO) REFERENCES DIM_ESTADO_PRESTAMO (ID_ESTADO_PRESTAMO),
	CONSTRAINT CHK_ESTADO_PAGO CHECK (
		NOT (
			INDICADOR_IMPAGO = TRUE
			AND INDICADOR_PAGADO_COMPLETO = TRUE
		)
	)
);

-- ============================================
-- TABLAS PUENTE
-- ============================================
CREATE TABLE BRIDGE_PRESTAMO_PRESTATARIO (
	ID_FACT_PRESTAMO BIGINT NOT NULL,
	ID_PRESTATARIO INTEGER NOT NULL,
	PORCENTAJE_PARTICIPACION NUMERIC(5, 2),
	PRIMARY KEY (ID_FACT_PRESTAMO, ID_PRESTATARIO),
	CONSTRAINT FK_BRIDGE_PP_FACT FOREIGN KEY (ID_FACT_PRESTAMO) REFERENCES FACT_PRESTAMO (ID_FACT_PRESTAMO),
	CONSTRAINT FK_BRIDGE_PP_PRESTATARIO FOREIGN KEY (ID_PRESTATARIO) REFERENCES DIM_PRESTATARIO (ID_PRESTATARIO),
	CONSTRAINT CHK_PARTICIPACION CHECK (
		PORCENTAJE_PARTICIPACION IS NULL
		OR (
			PORCENTAJE_PARTICIPACION >= 0
			AND PORCENTAJE_PARTICIPACION <= 100
		)
	)
);

CREATE TABLE BRIDGE_PRESTAMO_DESCUENTO (
	ID_FACT_PRESTAMO BIGINT NOT NULL,
	ID_DESCUENTO INTEGER NOT NULL,
	MONTO_DESCUENTO_TASA NUMERIC(5, 2) CHECK (MONTO_DESCUENTO_TASA >= 0),
	PRIMARY KEY (ID_FACT_PRESTAMO, ID_DESCUENTO),
	CONSTRAINT FK_BRIDGE_PD_FACT FOREIGN KEY (ID_FACT_PRESTAMO) REFERENCES FACT_PRESTAMO (ID_FACT_PRESTAMO),
	CONSTRAINT FK_BRIDGE_PD_DESCUENTO FOREIGN KEY (ID_DESCUENTO) REFERENCES DIM_DESCUENTO (ID_DESCUENTO)
);

-- ============================================
-- ÍNDICES OPCIONALES
-- ============================================
CREATE INDEX IDX_FACT_PRESTAMO_SUCURSAL ON FACT_PRESTAMO (ID_SUCURSAL);

CREATE INDEX IDX_FACT_PRESTAMO_TIPO ON FACT_PRESTAMO (ID_TIPO_PRESTAMO);

CREATE INDEX IDX_FACT_PRESTAMO_PROPOSITO ON FACT_PRESTAMO (ID_PROPOSITO);

CREATE INDEX IDX_FACT_PRESTAMO_TIEMPO_INICIO ON FACT_PRESTAMO (ID_TIEMPO_INICIO);

CREATE INDEX IDX_FACT_PRESTAMO_ESTADO ON FACT_PRESTAMO (ID_ESTADO_PRESTAMO);