SET SEARCH_PATH TO DW_BANCO;

TRUNCATE TABLE
    BRIDGE_PRESTAMO_DESCUENTO,
    BRIDGE_PRESTAMO_PRESTATARIO,
    FACT_PRESTAMO,
    DIM_TIEMPO,
    DIM_SUCURSAL,
    DIM_TIPO_PRESTAMO,
    DIM_PROPOSITO,
    DIM_PRESTATARIO,
    DIM_DESCUENTO,
    DIM_ESTADO_PRESTAMO
RESTART IDENTITY CASCADE;
